<?php
$pageTitle = 'Home';
require_once __DIR__ . '/includes/header.php';
?>
<section class="hero">
 <div class="container"><div class="row align-items-center g-5">
  <div class="col-lg-7"><span class="badge bg-primary-subtle text-primary rounded-pill px-3 py-2 mb-3">A better campus starts with being heard</span><h1>Report. Track. Resolve.<br><span class="text-primary">Together.</span></h1><p class="hero-copy mt-4">CampusCare gives students a clear, reliable way to raise concerns and gives administrators the tools to act on them.</p><div class="d-flex flex-wrap gap-3 mt-4"><a class="btn btn-primary btn-lg px-4" href="<?= e(url('auth/student-login.php')) ?>">Get started</a><a class="btn btn-outline-dark btn-lg px-4" href="<?= e(url('about.php')) ?>">How it works</a></div></div>
  <div class="col-lg-5"><div class="hero-panel"><div class="d-flex justify-content-between align-items-center mb-4"><div><div class="small text-white-50">Student dashboard</div><h5 class="mb-0">Complaint overview</h5></div><span class="badge bg-success-subtle text-success">Live</span></div><div class="row g-3"><div class="col-6"><div class="bg-white bg-opacity-10 rounded-3 p-3"><div class="text-white-50 small">Total complaints</div><div class="fs-2 fw-bold">12</div></div></div><div class="col-6"><div class="bg-white bg-opacity-10 rounded-3 p-3"><div class="text-white-50 small">Resolved</div><div class="fs-2 fw-bold text-success">08</div></div></div></div><div class="mt-4 p-3 rounded-3 bg-white bg-opacity-10"><div class="d-flex justify-content-between small mb-2"><span>Latest complaint</span><span class="text-white-50">#CC-2048</span></div><div class="fw-semibold">Library internet connectivity</div><div class="d-flex justify-content-between align-items-center mt-2"><span class="badge bg-warning-subtle text-warning">In Progress</span><span class="text-white-50 small">Updated today</span></div></div></div></div>
 </div></div>
</section>
<section class="py-5"><div class="container"><div class="text-center mb-5"><div class="text-primary fw-semibold small text-uppercase">Simple by design</div><h2 class="section-title mt-2">Everything you need to be heard</h2><p class="text-secondary">A focused platform for students, faculty, and administrators.</p></div><div class="row g-4"><div class="col-md-4"><div class="card h-100 p-4"><div class="feature-icon mb-3">01</div><h5>Raise concerns easily</h5><p class="text-secondary mb-0">Submit a detailed complaint with a category, priority, and optional supporting document.</p></div></div><div class="col-md-4"><div class="card h-100 p-4"><div class="feature-icon mb-3">02</div><h5>Stay informed</h5><p class="text-secondary mb-0">Follow progress from pending to resolved and see every administrator remark in one place.</p></div></div><div class="col-md-4"><div class="card h-100 p-4"><div class="feature-icon mb-3">03</div><h5>Actionable administration</h5><p class="text-secondary mb-0">Administrators can prioritize, update, and resolve complaints with a clear operational view.</p></div></div></div></div></section>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
